ci: display test result

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -15,3 +15,10 @@ jobs:
       run: .\scripts\_1_SetENV.ps1 && .\scripts\_3_Build.ps1
     - name: Test
       run: .\scripts\_1_SetENV.ps1 && .\scripts\_5_Tests.ps1
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: test-results           # Name of the check run which will be created
+        path: TestResults/jest-*.xml    # Path to test results
+        reporter: dotnet-trx        # Format of test results
